# Tensorflow
Start with having tensorflow installened in the enwironment.

## What is Tensorflow?
New data structures: tensors - multi-dimensional arrays (0-D tensor: scalar, 1-D tensor: vector, 2-D tensor: matrix, and so on)
Tensors can change shape – we can flatten matrix into vector, we can reshape matrix into 3-d tensor, etc.:

In [1]:
import tensorflow as tf
import numpy
d = tf.zeros((2,2))
e = tf.ones((2,2))
print(d)
print(e)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


See, these look like they are 2-D list, but in fact they are new data type -tensor. It has shape, 2-by-2 and type - these are real (Pyton data type float) numbers. Tensors have shape - dimensionality. 

    - The shape is defined by the length (number of elements) of each of the dimensions of a tensor.
    - Axis or Dimension: A particular dimension of a tensor.
    - Size: The total number of items in the tensor=the product of elements of shape vector
    
Tensors have data types (dtypes): int32/64), float, complex, uint8/16/32/64 (unsigned integer)
     
The rank of a tensor is the number of tensor dimensions:

     - A scalar has rank 0,
     - A vector has rank 1, 
     - A matrix is rank 2,
     - 3 dim array has rank 3,
     - A vector of 3 dimensional arrays has rank 4
     - A matrix of 3 dim arrays has rank 5, etc. 

To undearst what a vector of 3 dim arrays is you should think of a 3 dim array with division into subarrays (i.e. it is subdivided into 3-dim arrays aka batches). The value of the first coordinate is index number of a subarray and coordinates 2,3,4 define 3 dim tensors.

This is all ulike numbers that have no shape, rank, dimension, etc.

In [2]:
a = 2
b = 3
c = a+b
print(c)
print(c.get_shape())

5


AttributeError: 'int' object has no attribute 'get_shape'

numbers do not have shape - they are just python numbers, so no wonder we got error here. But we could do same addition of numbers and in the end get tensor. That is tf.add operation on 2 numbers conver them into tensors.  

In [3]:
c1 = tf.add(a,b,name='Add')
print(c1)

tf.Tensor(5, shape=(), dtype=int32)


If you think that numbers cannot be tensors, then you are incorrect. I can define numbers as tesnors and do same oeration on them. The difference is I at the same time created a computational graph, that I can reuse.

In [4]:
import tensorflow as tf
a1 = tf.constant(2)
b1 = tf.constant(3)
print(a1.get_shape())
c2 = tf.add(a1,b1,name='Add')
print(c2)

()
tf.Tensor(5, shape=(), dtype=int32)


I can reshape tensors and convert constant tesors to numbers applying conversion using numpy.

In [5]:
print(d)
print(tf.reshape(d,(1,4)))
a1=a1.numpy() #a1 now a number
a2=d.numpy() #a2 is 2-D list
print(a1, '\n', a2)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor([[0. 0. 0. 0.]], shape=(1, 4), dtype=float32)
2 
 [[0. 0.]
 [0. 0.]]


see a1 and a2 are no longer tensors so they do not have shapes

In [6]:
print(a1.get_shape())

AttributeError: 'numpy.int32' object has no attribute 'get_shape'

In [7]:
print(a2.get_shape())

AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'

In [8]:
tensor_3d=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]],dtype=float)
print(tensor_3d[1,1,0]) # as always in python idexes start with 0

tf.Tensor(7.0, shape=(), dtype=float32)


We can also change data types of tensors (provided such re-typing is available in python itself) using cast/recast operation

In [9]:
tensor_3d_int= tf.cast(tensor_3d, tf.int32)
print(tensor_3d_int)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


I create data types one from another. For example I can create  list of complex numbers as follows:

In [10]:
real = tf.constant([2.25, 3.25])
imag = tf.constant([4.75, 5.75])
y=tf.complex(real, imag) 
print(y)

tf.Tensor([2.25+4.75j 3.25+5.75j], shape=(2,), dtype=complex64)


Operations on tenrsors ‘*’ is product of two tensors means elementwise multiplication, + elementwise addition, tf.matmul or @-matrix multiplication

In [11]:
b=tf.constant([1,2])
A1 = tf.constant([[2, 24], [2, 26], [2, 57]])
x = [[1, 2, 3]]
C1 = tf.matmul(x, A1)+b
print(C1)

tf.Tensor([[ 13 249]], shape=(1, 2), dtype=int32)


Same with @ multiplication

In [12]:
y = x @ A1 + b
#print(w,'\n')
print(y)

tf.Tensor([[ 13 249]], shape=(1, 2), dtype=int32)


Broadcatsing: under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them. The simplest and most common case is when you attempt to multiply or add a tensor to a scalar 1 dim scalar by 2 dim, etc.

In [13]:
x=tf.constant([[1],[2], [3]])
print('x=',x)
y=tf.range(1,5)
print('y=',y)
c=x*y
print('product c=',c)

x= tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
y= tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
product c= tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Tensors of same common dimension can be concatenated along it

## Reducing sum and matrix operations

Reduce_sum is tf the reduction operation for the elementwise tf.math.add operation. Reduces input_tensor along the dimensions given in axis. Unless keepdims is true, the rank of the tensor is reduced by 1 for each of the entries in axis, which must be unique. If keepdims is true, the reduced dimensions are retained with length 1. If no dim are shown then it is done for all dimensions

In [15]:
print(e.get_shape())
c1=tf.reduce_sum(e)
print(c1)

(2, 2)
tf.Tensor(4.0, shape=(), dtype=float32)


In [16]:
print(c1.get_shape())

()


Matrices are special tensors that allow linear algeraic operations - trace, taking determinant, finding eigenvalues, eigen vectors, etc. It even has available SVD decomposition.

In [26]:
x=tf.constant([[1, 2, 3],[2, 3, 4],[3,4,7]],dtype=float) #inverse
y=tf.linalg.inv(x)
print(y)

tf.Tensor(
[[-2.5         0.99999994  0.5000002 ]
 [ 1.0000004   0.9999996  -0.99999994]
 [ 0.4999998  -0.99999976  0.49999994]], shape=(3, 3), dtype=float32)


In [27]:
detm=tf.linalg.det(x).numpy() #determinant
print(detm)

-2.0000005


In [28]:
z=tf.linalg.trace(x).numpy() #trace
print(z)

11.0


In [29]:
e_values, e_vectors = tf.linalg.eigh(y) #eigenvalues eigenvectores
print(e_values.numpy())

[-2.9331992  0.092613   1.8405868]


In [30]:
s, u, v = tf.linalg.svd(x) #SVD s -diagnal, U singular vectors of m-space v singular vectors of n-space
print(s,u,v)

tf.Tensor([10.797619    0.54330456  0.3409245 ], shape=(3,), dtype=float32) tf.Tensor(
[[ 0.34522298  0.12330939 -0.93038476]
 [ 0.4969536   0.8169342   0.29266968]
 [ 0.796152   -0.5633943   0.22074544]], shape=(3, 3), dtype=float32) tf.Tensor(
[[ 0.345223    0.12331032  0.9303847 ]
 [ 0.49695355  0.8169339  -0.29267055]
 [ 0.796152   -0.5633945  -0.2207449 ]], shape=(3, 3), dtype=float32)


## Tensordot operation

Very important linear algrebraic operation on tensors is outer-product (aka tensor product or tensordot). It is defined as follows. Let $A=(a_{i_1\ldots i_k})$ be $k$-dimesional tensor. And let $B=(b_{j_1 \ldots j_m})$ be $m$ dimesional tensor. Then $C=A\otimes B$ is an $k+m$ dimesional tensor such that $$C=(c_{t_1\ldots t_k t_{k+1} t_{k+m}})$$ where $$c_{t_1\ldots t_k t_{k+1} t_{k+m}} = a_{i_1\ldots i_k}\cdot b_{j_1 \ldots j_m}$$ for $$t_1=i_1,\ldots, t_k=i_k, t_{k+1}=j_1,\ldots,t_{k+m}=j_{k}.$$ For example, let $$C=
\begin{pmatrix}1&2&3\\2&3&4\end{pmatrix}⊗\begin{pmatrix}4&5\\ 5&6\\ 6&7\end{pmatrix}.$$ It is the outer product of 2-D tensor by 2-D tensor that is 4 dimesnional tensor. In this product the element $$c_{0,2,2,1}=a_{0,2}\cdot b_{2,1}=3\times 7=21$$ 

Notice that to have outer product we need to insdicate that axis over which we are doing the product is 0

In [31]:
x=tf.constant([[1, 2, 3],[2, 3, 4]])
y=tf.constant([[4, 5], [5, 6],[6, 7]])
xy0=tf.tensordot(x,y, axes = 0)
print(xy0)
print('xy0[0,2,2,1] is x[0,2]*y[2,1]=',xy0[0,2,2,1])

tf.Tensor(
[[[[ 4  5]
   [ 5  6]
   [ 6  7]]

  [[ 8 10]
   [10 12]
   [12 14]]

  [[12 15]
   [15 18]
   [18 21]]]


 [[[ 8 10]
   [10 12]
   [12 14]]

  [[12 15]
   [15 18]
   [18 21]]

  [[16 20]
   [20 24]
   [24 28]]]], shape=(2, 3, 3, 2), dtype=int32)
xy0[0,2,2,1] is x[0,2]*y[2,1]= tf.Tensor(21, shape=(), dtype=int32)


Note that standard Kronecker product of matrices is essentially flatenning of the outer product  C=X⊗Y into 2 dimesions, i.e. Kroneker product of matrices is just outer product C in which dimensions $i_0,i_2$ of outer product (the same as dimesnions with dimesions $k_0$ and $k_1$ of matrix $X$) and $i_3,i_4$ (the same $j_0,j_1$ of matrix $Y$) are flattened into two dimensiotn $s,t$ of Kroneker product matrix $D$, so that element $d_{st}=a_{k_0, k_1}\times b_{j_0,j_1}$ where $s=k_0\times j_0 $ and $t=k_1\times j_1$. So for example in the product  $$\begin{array}{lcl}
D=\begin{pmatrix}1&2&3\\2&3&4\end{pmatrix}⊗^K\begin{pmatrix}4&5\\5&6\\6&7\end{pmatrix}&=&\left(
   \begin{array} 1
1\cdot\begin{pmatrix}4&5\\5&6\\6&7\end{pmatrix}&2\cdot\begin{pmatrix}4&5\\5&6\\6&7\end{pmatrix}&3\cdot\begin{pmatrix}4&5\\5&6\\6&7\end{pmatrix}\\
2\cdot\begin{pmatrix}4&5\\5&6\\6&7\end{pmatrix}&3\cdot\begin{pmatrix}4&5\\5&6\\6&7\end{pmatrix}&4\cdot\begin{pmatrix}4&5\\5&6\\6&7\end{pmatrix}\\
\end{array}\right)\\ &=&\begin{pmatrix}4&5&8&10&12&15\\ 5&6&10&12&15&18\\6&7&16&14&18&21\\8&10&12&15&16&20\\10&12&15&18&20&24\\12&14&18&21&24&28\end{pmatrix}\end{array}$$ 
we have $d_{3,6}=21=d_{(1)\times (3),(3)\times(2)}=c_{1-1,3-1,3-1,2-1}=c_{0,2,2,1}$. Note that $1$ is subtracted everywhere in conversion because in tensorflow (as in Python) we count indices from $0$ not from $1$   

However, tensordot in tensorflow is much more than outer product thanks to definition of axis-to-axis reduction that we do not explicitly have in linear algebra. Tensordot is also tensor contraction in the sense that it sums the product of elements from tesnors $A$ and $B$ over the indices specified by $A$-axises and $B$-axises. The lists of pairs of $A$-axises and $B$-axises specify those pairs of axises along which to contract the tensors. The $A$-axis in pair $i$ must have the same dimension $B$ axis in pair $i$ for all pairs. For example 2D-tensor-dot operation of square matrices is nothing more than $A.B$ when axes 1 is multiplied to axes 0:

In [32]:
x=tf.constant([[1, 2, 3],[2, 3, 4]])
y=tf.constant([[4, 5], [5, 6],[6, 7]])
xy1=tf.tensordot(x,y, axes = (1,0))
print(xy1)

tf.Tensor(
[[32 38]
 [47 56]], shape=(2, 2), dtype=int32)


If I take axis more that number of dimesion (2 in case of matrices) then I will just flatten both tensors into vectors $\vec{x}=\begin{pmatrix} 1\\2\\3\\2\\3\\4\end{pmatrix}$ and $\vec{y}=\begin{pmatrix} 4\\5\\5\\6\\6\\7\end{pmatrix}$ in order of their indices and take a dot product of vectors $\sum_{i=1}^6 x_i\times y_i$

In [33]:
xy2=tf.tensordot(x,y, axes = 2)
print(xy2)

tf.Tensor(87, shape=(), dtype=int32)


Using indications which axis to merge with which I can do $A.B^T$ which will need too be axises 1 to 1, $A^T.B$ which is axises 0 to 0, $A^T.B^T$ which needs 0 to 1 or just normal product which is 1 to 0  and default that is performed when just one axis 1 is given

In [34]:
A = tf.constant([[1, 2, 3],
                 [1, 4, 2],
                 [3, 2, 1]])

B = tf.constant([[4, 1, 2],
                 [3, 4, 2],
                 [1, 2, 4]])
AB11=tf.tensordot(A,B, axes = ((1),(1)))
print(AB11)

tf.Tensor(
[[12 17 17]
 [12 23 17]
 [16 19 11]], shape=(3, 3), dtype=int32)


In [35]:
A = tf.constant([[1, 2, 3],
                 [1, 4, 2],
                 [3, 2, 1]])

B = tf.constant([[4, 1, 2],
                 [3, 4, 2],
                 [1, 2, 4]])
AB00=tf.tensordot(A,B, axes = ((0),(0)))
print(AB00)

tf.Tensor(
[[10 11 16]
 [22 22 20]
 [19 13 14]], shape=(3, 3), dtype=int32)


In [36]:
A = tf.constant([[1, 2, 3],
                 [1, 4, 2],
                 [3, 2, 1]])

B = tf.constant([[4, 1, 2],
                 [3, 4, 2],
                 [1, 2, 4]])
AB01=tf.tensordot(A,B, axes = ((0),(1)))
print(AB01)

tf.Tensor(
[[11 13 15]
 [16 26 18]
 [16 19 11]], shape=(3, 3), dtype=int32)
